// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1:string):Promise<any>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetActiveTasks():Promise<any>;

export function GetAllTasks():Promise<any>;

export function GetCompletedTasks():Promise<any>;

export function GetFilteredTasks(arg1:string):Promise<any>;

export function Greet(arg1:string):Promise<string>;

export function ToggleTask(arg1:number):Promise<any>;
