// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['main']['App']['AddTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetActiveTasks() {
  return window['go']['main']['App']['GetActiveTasks']();
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function GetCompletedTasks() {
  return window['go']['main']['App']['GetCompletedTasks']();
}

export function GetFilteredTasks(arg1) {
  return window['go']['main']['App']['GetFilteredTasks'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ToggleTask(arg1) {
  return window['go']['main']['App']['ToggleTask'](arg1);
}
